# Generated by Django 4.2.20 on 2025-03-29 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_admin_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpromotions',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.categories'),
        ),
        migrations.AlterField(
            model_name='productpromotions',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.products'),
        ),
    ]
