# Generated by Django 4.2.20 on 2025-03-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_categoryimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='img_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
