# Generated by Django 4.2.20 on 2025-03-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250330_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='core.users'),
        ),
    ]
